const portfolio = [
  {
    title: 'HTML & CSS',
    images: [
      './assets/images/bootstrap1.png',
      './assets/images/bootstrap2.png',
      './assets/images/bootstrap3.png',
    ],
    name: 'Bootstrap',
    deploy: 'https://ehlisn.github.io/bootstrap-ad-s-board/',
    link: 'https://github.com/EhlisN/bootstrap-ad-s-board',
    desc: 'Website built with Bootstrap 5 Framework',
  },
  {
    title: 'HTML & CSS',
    images: [
      './assets/images/responsive1.png',
      './assets/images/responsive2.png',
    ],
    name: 'Responsive',
    deploy: 'https://ehlisn.github.io/company-html-css/',
    link: 'https://github.com/EhlisN/company-html-css',
    desc: 'Responsive website using flex and media queries.',
  },
  {
    title: 'HTML & CSS',
    images: [
      './assets/images/mogo1.png',
      './assets/images/mogo2.png',
      './assets/images/mogo3.png',
      './assets/images/mogo4.png',
      './assets/images/mogo5.png',
    ],
    name: 'MoGo',
    deploy: 'https://ehlisn.github.io/MoGo-html-css/',
    link: 'https://github.com/EhlisN/MoGo-html-css',
    desc: 'Landing Page. Build with HTML & CSS.',
  },
  {
    title: 'JavaScript',
    images: [
      './assets/images/gamesJS1.png',
      './assets/images/gamesJS2.png',
      './assets/images/gamesJS3.png',
      './assets/images/gamesJS4.png',
      './assets/images/gamesJS5.png',
    ],
    name: 'Games',
    deploy: 'https://ehlisn.github.io/Games-JS/',
    link: 'https://github.com/EhlisN/Games-JS',
    desc: 'A small collection of simple JavaScript games: "Car", "Tic-tac-toe", "Cards", "15 Puzzle"',
  },
  {
    title: 'React',
    images: [
      './assets/images/brain-games1.png',
      './assets/images/brain-games2.png',
      './assets/images/brain-games3.png',
    ],
    name: 'Brain-games',
    deploy: 'https://ehlisn.github.io/brain-games-react/',
    link: 'https://github.com/EhlisN/brain-games-react',
    desc: 'Match The Tiles - make your brain work! Web application for various games and exercises for brain training. React, SPA, TypeScript.',
  },
  {
    title: 'React',
    images: ['./assets/images/products1.png', './assets/images/products2.png'],
    name: 'Products',
    deploy: 'https://ehlisn.github.io/Products-React/',
    link: 'https://github.com/EhlisN/Products-React/tree/main/Exam',
    desc: 'Simple React.TS Products listing using dummyjson.',
  },
  {
    title: 'Angular',
    images: ['./assets/images/weather1.png', './assets/images/weather2.png'],
    name: 'Weather',
    deploy: 'https://ehlisn.github.io/weather-angular/',
    link: 'https://github.com/EhlisN/weather-angular',
    desc: 'Weather app is the little web app for displaying the weather report from openweathermap.org using Components, Databinding, HTTP, Services, Observables, HTML5, CSS3 and more!',
  },
  {
    title: 'Angular',
    images: [
      './assets/images/movie1.png',
      './assets/images/movie2.png',
      './assets/images/movie3.png',
    ],
    name: 'Films',
    deploy: 'https://ehlisn.github.io/film-search-angular/',
    link: 'https://github.com/EhlisN/film-search-angular',
    desc: 'Application queries the OMDb API in order to retrieve information about requested movies. Pagination was implemented in order to display bigger search results. Application does not fully support responsive design but most of the components are built upon flex layouts and CSS grids so to make it fully usable on smaller devices.',
  },
];
